name: Zerocode TDD CI Build In Action

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setting up JDK8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Building and testing the changes
        run: mvn clean test -ntp -pl core -Dtest=**/HelloWorldInMemoryTest
